#!/usr/bin/env bash

#title|shsh
#version|0.4
#author|0ero1ne 
#info|Shell Script Manager 


# TODO
#   - 


# Global variables
version=0.4

# Script's absolute path
script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/bin"

# logo
header () 
{ 
	printf "\n%15s - %s\n\n" "[$(basename $0)]" "[v$version]"
}



# version
version ()
{
	printf "$(basename $0) $version\n"
}



# usage
usage ()
{
	printf """Usage: $(basename $0) [options] [package/keyword]

  -l, --list			list all scripts
  -s, --search <keyword>	search script using a keyword
  -i, --info 			view script info
  -h, --help			print this help
  -v, --version			current version

"""
	exit 0
}



# list function to output all script inside scr
script_list ()
{
	# iterate each file into the binaries folder and output the basename
	# grep the info line to show script's description
	for file in $script_dir/*; do
		printf "%-15s | " "$(basename $file)"
		printf "%-8s | " "$(awk -F'/' 'NR==1 {print $NF}' $file)"
		printf "%s\n" "$(egrep -m 1 '#info' $file | cut -d'|' -f2)"
	done; echo;

	exit 0
}


# search script by keyword
script_search() 
{
	return_code=1

	[ -z "$1" ] && printf "[error] missing search parameter\n" && exit 1

	for file in $script_dir/*; do
		if [ "$(egrep -m 1 '#info' $file | egrep $1)" ]; then
			printf "[%s]\n" "$(basename $file)"
			printf "  %s\n" "$(egrep -m 1 '#info' $file | egrep $1 | awk -F'|' '{print $2}')" 

			return_code=0
		fi
	done
	
	[ "$return_code" -eq 1 ] && printf "[error] no script found\n" && exit 1

	exit 0
}



# retrive script info
script_info ()
{
	# check if arg is not empty
	[ -z "$1" ] && printf "[error] missing script name\n\n" && exit 1

	# check if file exist and is a regular file
	[ ! -f "$script_dir/${1}" ] && printf "[error] file not found\n\n" && exit 1

	# egrep check for the first value and if finds it will ouput
	# if no patterns are found will return blank
	printf "%15s | %s\n" "title" "$(egrep -m 1 '#title' $script_dir/${1} | cut -d'|' -f2)"
	printf "%15s | %s\n" "version" "$(egrep -m 1 '#version' $script_dir/${1} | cut -d'|' -f2)"
	printf "%15s | %s\n" "author" "$(egrep -m 1 '#author' $script_dir/${1} | cut -d'|' -f2)"
	printf "%15s | %s\n" "info" "$(egrep -m 1 '#info' $script_dir/${1} | cut -d'|' -f2)"
	printf "\n"

	exit 0
}



# arg_parser
arg_parser ()
{
	# Check if there is no argument and if true show usage and exit 1
	[ $# -eq 0 ] && usage exit 1

	# Cycle all the arguments 
	for args in $@
	do
		# Parse each argument to its function and set 
		case $args in
			-l | --list) 	header; script_list						;;
			-s | --search)	header; script_search	"$2" ; shift 2	;;
			-i | --info)	header;	script_info		"$2" ; shift 2	;;
			-h | --help)			usage							;;
			-v | --version) 		version 						;;
			*)						usage							;;
		esac
	done
}



# Init
arg_parser "$@"
