#!/usr/bin/env bash

#title|shsh
#version|0.3
#author|0ero1ne 
#info|Shell Script Manager 


# TODO
#   - check for errors
#	- 


# Global variables
version=0.1
script_dir='bin'

red=\033[


# logo
logo () 
{ 
	printf "\n%15s | %s\n\n" "[$0]" "[v$version]"
}



# version
version ()
{
	printf "$0 $version\n"
}



# usage
usage ()
{
	printf """
$0 <parameter> 

  -l, --list			list all scripts
  -s, --search <keyword>	search script using a keyword
  -i, --info 			view script info
  -h, --help			print this help
  -v, --version			current version

"""
	exit 0
}



# list function to output all script inside scr
script_list ()
{
	# iterate each file into the binaries folder and output the basename
	# grep the info line to show script's description
	for file in $script_dir/*; do
		printf "%-10s | " "$(basename $file)"
		printf "%-8s | " "$(awk -F'/' 'NR==1 {print $NF}' $file)"
		printf "%s\n" "$(egrep -m 1 '#info' $file | cut -d'|' -f2)"
	done; echo;

	exit 0
}


# search script by keyword
script_search() 
{
	return_code=1

	[ -z "$1" ] && printf "[error] missing search parameter\n" && exit 1

	for file in $script_dir/*; do
		if sed -n '3,6p' $file | grep -q $1; then	
			printf "%s%s\n" "${file%%.*}" "$(awk -F: 'NR==4 {print $2}' $file)" 
			printf "%s\n\n" "$(awk -F: 'NR==6 {print $2}' $file)"
			
			return_code=0
		fi
	done
	
	[ "$return_code" -eq 1 ] && printf "[error] no script found\n" && exit 1

	exit 0
}



# retrive script info
script_info ()
{
	# check if arg is not empty
	[ -z "$1" ] && printf "[error] missing script name\n\n" && exit 1

	# check if file exist and is a regular file
	[ ! -f "$script_dir/${1}" ] && printf "[error] file not found\n\n" && exit 1

	# extract the information from the file
	#awk -F: 'NR==3,NR==6 {printf "%15s |%s\n", substr($1,3), $2}' $script_dir/${1}.sh
	
	# egrep check for the first value and if finds it will ouput
	# if no patterns are found will return blank
	printf "%15s | %s\n" "title" "$(egrep -m 1 '#title' $script_dir/${1} | cut -d'|' -f2)"
	printf "%15s | %s\n" "version" "$(egrep -m 1 '#version' $script_dir/${1} | cut -d'|' -f2)"
	printf "%15s | %s\n" "author" "$(egrep -m 1 '#author' $script_dir/${1} | cut -d'|' -f2)"
	printf "%15s | %s\n" "info" "$(egrep -m 1 '#info' $script_dir/${1} | cut -d'|' -f2)"
	printf "\n"

	exit 0
}



# arg_parser
arg_parser ()
{
	# Check if there is no argument and if true show usage and exit 1
	[ $# -eq 0 ] && usage exit 1

	# Cycle all the arguments 
	for args in $@
	do
		# Parse each argument to its function and set 
		case $args in
			-l | --list) 	logo; 	script_list						;;
			-s | --search)	logo; 	script_search	"$2" ; shift 2	;;
			-i | --info)	logo;	script_info		"$2" ; shift 2	;;
			-h | --help)			usage							;;
			-v | --version) 		version 						;;
			*)						usage							;;
		esac
	done
}



# Init
arg_parser "$@"
